//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataOrganization.Core.Infrastructure.DB
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Defines the <see cref="Field" />.
    /// </summary>
    public partial class Field
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Field"/> class.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.Contents = new HashSet<Content>();
        }

        /// <summary>
        /// Gets or sets the Id.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the Field1.
        /// </summary>
        public string Field1 { get; set; }

        /// <summary>
        /// Gets or sets the IdFile.
        /// </summary>
        public Nullable<int> IdFile { get; set; }

        /// <summary>
        /// Gets or sets the Contents.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }

        /// <summary>
        /// Gets or sets the File.
        /// </summary>
        public virtual File File { get; set; }
    }
}
